export type Item = {
  label: string;
  url: string;
};

export const cssInJsLibs: Item[] = [
  { label: 'Aphrodite', url: 'https://github.com/Khan/aphrodite' },
  { label: 'astroturf', url: 'https://github.com/4Catalyzer/astroturf' },
  { label: 'Classy', url: 'https://inturn.github.io/classy/' },
  { label: 'CSJS', url: 'https://github.com/rtsao/csjs' },
  {
    label: 'CSS constructor',
    url: 'https://github.com/siddharthkp/css-constructor',
  },
  { label: 'Emotion', url: 'https://emotion.sh/' },
  { label: 'Fela', url: 'https://fela.js.org/' },
  { label: 'freestyler', url: 'https://github.com/streamich/freestyler' },
  { label: 'glamor', url: 'https://github.com/threepointone/glamor' },
  { label: 'glamorous', url: 'https://glamorous.rocks/' },
  { label: 'goober', url: 'https://github.com/cristianbote/goober' },
  { label: 'JSS', url: 'https://cssinjs.org/' },
  { label: 'jsxstyle', url: 'https://github.com/jsxstyle/jsxstyle' },
  { label: 'Linaria', url: 'https://linaria.dev/' },
  { label: 'nano-css', url: 'https://github.com/streamich/nano-css' },
  { label: 'radium', url: 'https://formidable.com/open-source/radium/' },
  { label: 'reshadow', url: 'https://reshadow.dev/' },
  { label: 'Stitches', url: 'https://stitches.dev/' },
  { label: 'style-it', url: 'https://github.com/buildbreakdo/style-it' },
  { label: 'styled-components', url: 'https://styled-components.com/' },
  { label: 'Stylerun', url: 'https://artalar.github.io/stylerun/' },
  { label: 'Styletron', url: 'https://styletron.org/' },
  { label: 'treat', url: 'https://github.com/seek-oss/treat' },
  { label: 'TypeStyle', url: 'https://typestyle.github.io/' },
  { label: 'ui-box', url: 'https://github.com/segmentio/ui-box' },
  { label: 'xstyled', url: 'https://xstyled.dev/' },
];

export const stateManagers: Item[] = [
  { label: 'ActiveJS', url: 'https://activejs.dev/' },
  { label: 'Constate', url: 'https://github.com/diegohaz/constate' },
  { label: 'Easy Peasy', url: 'https://easy-peasy.now.sh/' },
  { label: 'effector', url: 'https://effector.dev/' },
  { label: 'Faste', url: 'https://github.com/theKashey/faste' },
  { label: 'Focal', url: 'https://github.com/grammarly/focal' },
  { label: 'Jotai', url: 'https://jotai.surge.sh/' },
  { label: 'Microstates', url: 'https://github.com/thefrontside/microstates' },
  { label: 'MobX', url: 'https://mobx.js.org/' },
  { label: 'Overmind', url: 'https://overmindjs.org/' },
  { label: 'Parket', url: 'https://github.com/ForsakenHarmony/parket' },
  { label: 'Reatom', url: 'https://reatom.js.org/' },
  { label: 'Reclare', url: 'https://github.com/oguzgelal/reclare' },
  { label: 'Recoil', url: 'https://recoiljs.org/' },
  { label: 'Redux', url: 'https://redux.js.org/' },
  { label: 'reistore', url: 'https://github.com/Wroud/reistore' },
  { label: 'Robot', url: 'https://thisrobot.life/' },
  { label: 'Storeon', url: 'https://github.com/storeon/storeon' },
  { label: 'Undux', url: 'https://undux.org/' },
  { label: 'unistore', url: 'https://github.com/developit/unistore' },
  { label: 'Unstated', url: 'https://github.com/jamiebuilds/unstated' },
  {
    label: 'Unstated Next',
    url: 'https://github.com/jamiebuilds/unstated-next',
  },
  { label: 'Valtio', url: 'https://github.com/pmndrs/valtio' },
  { label: 'XState', url: 'https://xstate.js.org/' },
  { label: 'Zedux', url: 'https://github.com/bowheart/zedux' },
  { label: 'Zustand', url: 'https://zustand.surge.sh/' },
];
